# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='landing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_description', models.CharField(max_length=500)),
                ('about_us_description1', models.CharField(max_length=500)),
                ('about_us_description2', models.CharField(max_length=500)),
                ('goal_title', models.CharField(max_length=500)),
                ('goal_description', models.CharField(max_length=1000)),
                ('landing_background1', models.CharField(max_length=100)),
                ('landing_background2', models.CharField(max_length=100)),
                ('landing_background3', models.CharField(max_length=100)),
            ],
        ),
    ]
