# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=30)),
                ('service_description', models.CharField(max_length=100)),
                ('service_logo_link', models.CharField(max_length=200)),
            ],
        ),
    ]
