# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='service_logo_link',
            new_name='service_logo_ionicon_name',
        ),
    ]
