# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_logo_img', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_address', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=100)),
                ('address_x', models.CharField(max_length=20)),
                ('address_y', models.CharField(max_length=20)),
                ('company_facebook', models.CharField(max_length=100)),
                ('company_linkedin', models.CharField(max_length=100)),
                ('company_twitter', models.CharField(max_length=100)),
                ('company_instagram', models.CharField(max_length=100)),
            ],
        ),
    ]
